#!/usr/bin/env node
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const dataDirectory = path.join(root, "data");
const cacheDirectory = path.join(root, ".cache");
const sourceCommit = "923b108dc5d45dee061324c011b478fb649f8b73";
const gapLimit = 64;
const arguments_ = new Set(process.argv.slice(2));
for (const argument of arguments_) {
  assert(["--offline", "--check", "--help"].includes(argument), `Unknown option: ${argument}`);
}

if (arguments_.has("--help")) {
  console.log("Usage: node experimental/initials/scripts/generate-data.mjs [--offline] [--check]\nUses fixed source-lock.json URLs and SHA-256 hashes. --offline requires the existing verified cache; --check compares generated bytes without changing data files.");
  process.exit(0);
}

const lock = JSON.parse(await readFile(path.join(dataDirectory, "source-lock.json"), "utf8"));
assert.equal(lock.formatVersion, 1);
assert.equal(lock.sourceCommit, sourceCommit);
assert.equal(new Set(lock.sources.map(source => source.id)).size, lock.sources.length);
const hash = bytes => createHash("sha256").update(bytes).digest("hex");
const codePointLabel = codePoint => `U+${codePoint.toString(16).toUpperCase().padStart(4, "0")}`;

async function sourceBytes(source) {
  assert.equal(path.basename(source.cacheFile), source.cacheFile, "Cache filenames must be flat");
  const url = new URL(source.url);
  assert.equal(url.protocol, "https:");
  assert(["raw.githubusercontent.com", "www.unicode.org"].includes(url.hostname));
  assert(!url.username && !url.password, "Sources must not use credentials");
  const filename = path.join(cacheDirectory, source.cacheFile);
  let bytes;
  try {
    bytes = await readFile(filename);
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
    assert(!arguments_.has("--offline"), `Offline cache is missing: ${source.cacheFile}`);
    let lastError;
    for (let attempt = 0; attempt < 3; attempt += 1) {
      try {
        const response = await fetch(url, {
          credentials: "omit", redirect: "error", signal: AbortSignal.timeout(30000),
        });
        assert(response.ok, `${source.id}: HTTP ${response.status}`);
        bytes = Buffer.from(await response.arrayBuffer());
        break;
      } catch (error_) {
        lastError = error_;
      }
    }
    if (!bytes) throw lastError;
    assert.equal(bytes.length, source.size, `${source.id}: downloaded byte count changed`);
    assert.equal(hash(bytes), source.sha256, `${source.id}: downloaded SHA-256 changed`);
    await mkdir(cacheDirectory, { recursive: true });
    await writeFile(filename, bytes);
  }
  assert.equal(bytes.length, source.size, `${source.id}: cached byte count changed`);
  assert.equal(hash(bytes), source.sha256, `${source.id}: cached SHA-256 changed`);
  return bytes;
}

const sources = new Map(await Promise.all(lock.sources.map(async source => [source.id, await sourceBytes(source)])));

function parseReadings(bytes, name) {
  const records = new Map();
  const invalidReadings = [];
  for (const [index, rawLine] of bytes.toString("utf8").split(/\r?\n/).entries()) {
    const line = rawLine.split("#", 1)[0].trim();
    if (!line) continue;
    const match = /^U\+([0-9A-F]{4,6}):\s*(.+)$/.exec(line);
    assert(match, `${name}:${index + 1}: invalid record`);
    const codePoint = Number.parseInt(match[1], 16);
    assert(codePoint <= 0x10ffff && !(codePoint >= 0xd800 && codePoint <= 0xdfff));
    assert(!records.has(codePoint), `${name}: duplicate ${codePointLabel(codePoint)}`);
    const readings = match[2].split(",").map(reading => reading.trim());
    assert(readings.every(Boolean), `${name}: empty pronunciation at ${codePointLabel(codePoint)}`);
    for (const reading of readings) {
      if (!initial(reading)) invalidReadings.push({ codePoint: codePointLabel(codePoint), character: String.fromCodePoint(codePoint), reading });
    }
    records.set(codePoint, readings);
  }
  return { records, invalidReadings };
}

function initial(reading) {
  // First Latin letter of Hanyu Pinyin, not the full shengmu (zh/ch/sh).
  const first = [...reading.normalize("NFD").replace(/\p{M}/gu, "")][0];
  if (!first || !/^[A-Za-z]$/.test(first)) return null;
  return first.toUpperCase();
}

function makeRanges(entries) {
  const ranges = [];
  let start;
  let previous;
  let letters = "";
  for (const [codePoint, letter] of entries) {
    if (previous === undefined || codePoint - previous - 1 > gapLimit) {
      if (previous !== undefined) ranges.push([start, letters]);
      start = codePoint;
      letters = letter;
    } else {
      letters += ".".repeat(codePoint - previous - 1) + letter;
    }
    previous = codePoint;
  }
  if (previous !== undefined) ranges.push([start, letters]);
  return ranges;
}

const full = parseReadings(sources.get("pinyin-full"), "pinyin.txt");
const common = parseReadings(sources.get("pinyin-common"), "kMandarin_8105.txt");
assert.equal(common.records.size, 8105);
assert([...common.records.values()].every(readings => readings.length === 1));

function buildDataset(name, inventory) {
  const entries = new Map();
  const alternatives = {};
  const invalidDefaults = [];
  let commonPreferredEntries = 0;
  let commonPreferredInitialChanges = 0;
  const commonPreferredChanges = [];
  let chosenInitialAbsentFromFull = 0;
  for (const codePoint of [...inventory.keys()].sort((a, b) => a - b)) {
    const preferred = common.records.get(codePoint) ?? inventory.get(codePoint);
    const defaultInitial = initial(preferred[0]);
    if (!defaultInitial) {
      invalidDefaults.push({ codePoint: codePointLabel(codePoint), character: String.fromCodePoint(codePoint), reading: preferred[0] });
      continue;
    }
    if (common.records.has(codePoint)) {
      commonPreferredEntries += 1;
      if (full.records.has(codePoint) && initial(full.records.get(codePoint)[0]) !== defaultInitial) {
        commonPreferredInitialChanges += 1;
        commonPreferredChanges.push({
          codePoint: codePointLabel(codePoint), character: String.fromCodePoint(codePoint),
          fullFirstReading: full.records.get(codePoint)[0], preferredReading: preferred[0],
        });
      }
    }
    entries.set(codePoint, defaultInitial);
    const sourceInitials = (full.records.get(codePoint) ?? inventory.get(codePoint)).map(initial).filter(Boolean);
    if (full.records.has(codePoint) && !sourceInitials.includes(defaultInitial)) chosenInitialAbsentFromFull += 1;
    // Place the chosen default first; preserve source order for all remaining letters.
    const candidates = [...new Set([defaultInitial, ...sourceInitials])].join("");
    if (candidates.length > 1) alternatives[String.fromCodePoint(codePoint)] = candidates;
  }
  const ranges = makeRanges(entries);
  const reconstructed = new Map();
  for (const [start, letters] of ranges) {
    assert(/^[A-Z.]+$/.test(letters));
    assert(!letters.startsWith(".") && !letters.endsWith("."));
    assert(!letters.includes(".".repeat(gapLimit + 1)));
    for (let offset = 0; offset < letters.length; offset += 1) {
      if (letters[offset] !== ".") reconstructed.set(start + offset, letters[offset]);
    }
  }
  assert.deepEqual(reconstructed, entries, `${name}: range round-trip mismatch`);
  for (const [character, candidates] of Object.entries(alternatives)) {
    assert.equal([...character].length, 1);
    assert(/^[A-Z]{2,26}$/.test(candidates));
    assert.equal(new Set(candidates).size, candidates.length);
    assert.equal(entries.get(character.codePointAt(0)), candidates[0]);
  }
  const missingLegacyCodePoints = [];
  for (let codePoint = 0x4e00; codePoint <= 0x9fa5; codePoint += 1) {
    if (!entries.has(codePoint)) missingLegacyCodePoints.push({ codePoint: codePointLabel(codePoint), character: String.fromCodePoint(codePoint) });
  }
  const positions = [...entries.keys()];
  const slots = ranges.reduce((count, [, letters]) => count + letters.length, 0);
  return {
    dataset: { name, sourceCommit, entries: entries.size, ranges, alternatives },
    report: {
      inventorySource: name === "modern-common" ? "kMandarin_8105.txt" : "pinyin.txt",
      sourceRecords: inventory.size, entries: entries.size, ranges: ranges.length,
      rangeSlots: slots, unknownHoleSlots: slots - entries.size,
      bmpEntries: positions.filter(codePoint => codePoint <= 0xffff).length,
      supplementaryEntries: positions.filter(codePoint => codePoint > 0xffff).length,
      minCodePoint: codePointLabel(positions[0]), maxCodePoint: codePointLabel(positions.at(-1)),
      alternativesEntries: Object.keys(alternatives).length,
      commonPreferredEntries, commonPreferredInitialChanges, commonPreferredChanges, chosenInitialAbsentFromFull,
      invalidDefaults, missingLegacyCount: missingLegacyCodePoints.length,
      ...(name === "modern-full" ? { missingLegacyCodePoints } : {}),
    },
  };
}

const generated = [buildDataset("modern-common", common.records), buildDataset("modern-full", full.records)];
function readingCounts(source) {
  const readings = [...source.records.values()];
  const multipleReadingRecords = readings.filter(items => items.length > 1).length;
  const multipleInitialRecords = readings.filter(items => new Set(items.map(initial).filter(Boolean)).size > 1).length;
  return {
    records: source.records.size, multipleReadingRecords, multipleInitialRecords,
    multipleReadingsCollapsedToOneInitial: multipleReadingRecords - multipleInitialRecords,
    invalidReadings: source.invalidReadings,
  };
}
const generationReport = {
  formatVersion: 1, sourceCommit, upstreamUnicodeVersion: lock.upstreamUnicodeVersion,
  rangeGapLimit: gapLimit,
  defaultPolicy: "Prefer the kMandarin_8105.txt reading when that character is present; otherwise use the first pinyin.txt reading. The latter is the upstream ordering, not a frequency or contextual guarantee.",
  alternativesPolicy: "Both inventories use all matching pinyin.txt readings. Strip combining marks using NFD, take the first ASCII Latin letter, deduplicate in source order, then move the chosen default first. Store only characters with at least two distinct initials.",
  limitations: [
    "Candidate readings may include historical or rare readings. Candidate matching does not choose a contextually appropriate pronunciation.",
    "First-letter conversion is not full pinyin or shengmu extraction. Tone and remaining syllable letters are intentionally discarded.",
    "Characters absent from an inventory, including period-marked range holes, remain the runtime's responsibility; this generator does not guess readings.",
    "Neither inventory promises all Unicode Han characters or complete replacement coverage of the legacy 20,902-character table.",
  ],
  sourceCounts: {
    full: readingCounts(full),
    common: readingCounts(common),
  },
  datasets: Object.fromEntries(generated.map(({ dataset, report }) => [dataset.name, report])),
};

async function output(relativePath, bytes) {
  const destination = path.join(dataDirectory, relativePath);
  if (arguments_.has("--check")) {
    assert((await readFile(destination)).equals(Buffer.from(bytes)), `${relativePath}: generated bytes differ`);
  } else {
    await mkdir(path.dirname(destination), { recursive: true });
    await writeFile(destination, bytes);
  }
}

for (const { dataset } of generated) await output(`${dataset.name}.json`, JSON.stringify(dataset) + "\n");
await output("generation-report.json", JSON.stringify(generationReport, null, 2) + "\n");
for (const source of lock.sources) {
  if (source.licenseFile) await output(source.licenseFile, sources.get(source.id));
  if (source.attributionFile) await output(source.attributionFile, sources.get(source.id));
}
console.log(JSON.stringify({ mode: arguments_.has("--check") ? "verified" : "generated", sourceCommit, datasets: generated.map(({ dataset, report }) => ({ name: dataset.name, entries: dataset.entries, ranges: dataset.ranges.length, alternatives: report.alternativesEntries, invalidDefaults: report.invalidDefaults.length })) }, null, 2));
